In [1]:
import pandas as pd
import numpy as np

In [2]:
nav = pd.read_csv("../data/raw/02_nav_history.csv")

In [3]:
nav.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [4]:
nav.columns

Index(['amfi_code', 'date', 'nav'], dtype='str')

In [5]:
nav.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [6]:
nav.duplicated().sum()

np.int64(0)

In [7]:
nav=nav.drop_duplicates()

In [8]:
nav["date"] = pd.to_datetime(nav["date"])

In [9]:
nav = nav.sort_values(
    ["amfi_code","date"]
)

In [10]:
nav["nav"] = nav.groupby(
    "amfi_code"
)["nav"].ffill()

In [11]:
(nav["nav"] > 0).sum()

np.int64(46000)

In [12]:
(nav["nav"] <= 0).sum()

np.int64(0)

In [13]:
nav.to_csv(
    "../data/processed/clean_nav_history.csv",
    index=False
)

## Cleaning Performed on nav_history.csv

- Converted date column to datetime format.
- Sorted data by amfi_code and date.
- Checked for duplicate rows and removed them.
- Verified there were no missing NAV values.
- Applied forward-fill logic (no changes because there were no missing values).
- Validated that all NAV values are greater than 0.
- Saved cleaned dataset as clean_nav_history.csv.

In [14]:
transactions = pd.read_csv("../data/raw/08_investor_transactions.csv")

In [15]:
transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [17]:
transactions.columns

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')

In [18]:
transactions.dtypes

investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

In [19]:
transactions["transaction_date"] = pd.to_datetime(transactions["transaction_date"])

In [20]:
transactions["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [21]:
transactions["transaction_type"] = transactions["transaction_type"].str.strip().str.title()

In [22]:
transactions["transaction_type"].unique()

<StringArray>
['Sip', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [23]:
transactions["transaction_type"] = transactions["transaction_type"].replace({
    "Sip": "SIP",
    "Lumpsum": "Lumpsum",
    "Redemption": "Redemption"
})

In [24]:
transactions["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [25]:
(transactions["amount_inr"] <= 0).sum()

np.int64(0)

In [26]:
transactions["kyc_status"].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [27]:
transactions["kyc_status"].value_counts()

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

In [28]:
transactions.duplicated().sum()

np.int64(0)

In [29]:
transactions = transactions.drop_duplicates()

In [30]:
transactions.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [31]:
transactions.to_csv("../data/processed/clean_investor_transactions.csv", index=False)

## Cleaning Performed on investor_transactions.csv

- Converted transaction_date to datetime format.
- Verified transaction types (SIP, Lumpsum, Redemption).
- Standardized transaction_type formatting.
- Validated all transaction amounts are greater than 0.
- Verified KYC status values (Verified, Pending).
- Checked for duplicate rows and removed if present.
- Saved cleaned dataset as clean_investor_transactions.csv.

In [32]:
performance = pd.read_csv("../data/raw/07_scheme_performance.csv")

In [33]:
performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [34]:
performance.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

In [35]:
performance.dtypes

amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

In [36]:
return_columns = [
    "return_1yr_pct",
    "return_3yr_pct",
    "return_5yr_pct"
]

for col in return_columns:
    performance[col] = pd.to_numeric(performance[col], errors="coerce")

In [37]:
performance[return_columns].isnull().sum()

return_1yr_pct    0
return_3yr_pct    0
return_5yr_pct    0
dtype: int64

In [39]:
performance["expense_ratio_pct"].describe()

count    40.000000
mean      1.237000
std       0.386584
min       0.550000
25%       0.787500
50%       1.425000
75%       1.540000
max       1.640000
Name: expense_ratio_pct, dtype: float64

In [40]:
performance[
    (performance["expense_ratio_pct"] < 0.1) |
    (performance["expense_ratio_pct"] > 2.5)
]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [41]:
performance.duplicated().sum()

np.int64(0)

In [42]:
performance = performance.drop_duplicates()

In [43]:
performance.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [44]:
performance.to_csv(
    "../data/processed/clean_scheme_performance.csv",
    index=False
)

## Cleaning Performed on scheme_performance.csv

- Validated return columns are numeric.
- Converted return columns to numeric using pd.to_numeric().
- Checked for invalid return values.
- Verified expense ratio is between 0.1% and 2.5%.
- Checked for duplicate rows and removed if present.
- Saved cleaned dataset as clean_scheme_performance.csv.